name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest
        name: 'Lint'
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: pcov

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer update --no-interaction --verbose

            - name: Check platform requirements
              run: composer check-platform-reqs --verbose

            - name: PHP-CS-Fixer
              run: composer fix -- --dry-run --verbose

            # - name: composer normalize
            #   run: composer normalize --dry-run --no-interaction --verbose

            # - name: test coverage
            #   run: |
            #       ./vendor/bin/phpunit --coverage-clover=coverage.xml --debug --verbose
            #       bash <(curl -s https://codecov.io/bash)
            #   env:
            #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            # - name: Infection
            #   run: ./vendor/bin/infection --show-mutations --min-covered-msi=100 --no-progress --no-interaction --verbose
              # env:
              #     INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}

            # - name: Psalm
            #   run: ./vendor/bin/psalm --shepherd --no-progress

            # - name: PHPStan
            #   run: ./vendor/bin/phpstan --no-interaction --verbose
            #
            #   composer-require-checker
            #   composer-unused

    tests:
        runs-on: ubuntu-latest
        name: 'Test suite on PHP: ${{ matrix.php }}; Dependecies: ${{ matrix.dependency-version }}'
        strategy:
            matrix:
                php: ['8.0', '8.1', '8.2']
                laravel: ['^8.12', '^9.0']
                dependency-version: ['prefer-lowest', 'prefer-stable']
                include:
                    - testbench: '^6.0'
                      laravel: '^8.12'
                    - testbench: '^7.0'
                      laravel: '^9.0'

        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Get composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: ${{ steps.composer-cache.outputs.dir }}
                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                restore-keys: ${{ runner.os }}-composer-

            - name: Remove dev packages
              run: |
                  composer remove --dev --no-update --no-interaction --verbose \
                      friendsofphp/php-cs-fixer \
                      infection/infection \
                      nunomaduro/larastan \
                      phpstan/phpstan-strict-rules

            - name: Require Laravel and testbench version
              run: composer require laravel/framework:"${{ matrix.laravel }}" illuminate/collections:"${{ matrix.laravel }}" illuminate/database:"${{ matrix.laravel }}" illuminate/http:"${{ matrix.laravel }}" illuminate/support:"${{ matrix.laravel }}" orchestra/testbench:"${{ matrix.testbench }}"  --no-update --no-interaction --verbose --with-all-dependencies


            - name: Support prefer-lowest in PHP 8.0
              if: ${{ matrix.php == 8.0 && matrix.dependency-version == 'prefer-lowest' }}
              run: composer require mockery/mockery:"^1.3.3" --no-update

            - name: Support prefer-lowest in PHP 8.1
              if: ${{ matrix.php == 8.2 && matrix.dependency-version == 'prefer-lowest' }}
              run: composer require symfony/http-foundation:"^5.3.7 || ^6.0" laravel/framework:"^8.53 || ^9.0" --no-update

            - name: Support prefer-lowest in PHP 8.2
              if: ${{ matrix.php == 8.2 && matrix.dependency-version == 'prefer-lowest' }}
              run: composer require nesbot/carbon:"^2.62.1" --no-update



            - name: Install dependencies
              run: composer update --${{ matrix.dependency-version }} --no-interaction --verbose

            - name: Check platform requirements
              run: composer check-platform-reqs --verbose

            - name: Run tests
              run: composer test
